name: Build and deploy


on:
  push:
    branches: [ main ]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Heroku deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku container:login
          heroku container:push -a STT_bot worker
          heroku container:release -a STT_bot worker
